return function( cfg )
	cfg.Hide_All_Mods=true
	cfg.safespack_01=true
	cfg.safesast_01=true
	cfg.safesburn_01=true
	cfg.safessfs_01=true
	cfg.announcements=false
	cfg.safesmxs_01=true
	cfg.RSSFeed=false
	cfg.HUD_MovingText=false
	cfg.safesevent_dinner=true
	cfg.AimbotInfAmmo=true
	cfg.safescat_01=true
	cfg.safesait_01=true
	cfg.Hide_Pirate_Perfection=true
	cfg.NoDropinPause=true
	cfg.const_blt_version="2.3 (r7_r19)"
	cfg.safesgrunt_01=true
	cfg.const_creator="Baddog-11"
	cfg.const_edition="Patron Edition"
	cfg.safesoverkill_01=false
	cfg.DebugElementsAdditional=true
	cfg.safesdallas_01=true
	cfg.KillAllIgnoreCivilians=false
	cfg.DLCUnlocker=true
	cfg.safesevent_red=true
	cfg.non_modded_lobby=true
	cfg.safesweapon_01=true
	cfg.safesdss_01=true
	cfg.safeswwt_01=true
	cfg.safescss_01=true
	cfg.menu_save=true
	cfg.safesbuck_01=true
	cfg.DebugAdditionalEsp=true
	cfg.PreventEquipDetecting=true
	cfg.safesnin_01=true
	cfg.jobmenu_def_difficulty="One Down"
	cfg.DebugMissionElements=true
end
